path: "tensorflow.tpu.experimental.DeviceOrderMode"
tf_class {
  is_instance: "<enum \'DeviceOrderMode\'>"
  member {
    name: "AUTO"
    mtype: "<enum \'DeviceOrderMode\'>"
  }
  member {
    name: "MESH"
    mtype: "<enum \'DeviceOrderMode\'>"
  }
  member {
    name: "RING"
    mtype: "<enum \'DeviceOrderMode\'>"
  }
  member_method {
    name: "__format__"
  }
  member_method {
    name: "__new__"
    argspec: "args=[\'cls\', \'value\'], varargs=None, keywords=None, defaults=None"
  }
}
